title: IRRI Bioinformatics Portal
description: Bioinformatics Portal Webpage
theme: jekyll-theme-minimal
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-sitemap
# Minimal Mistakes specific options (if you install the theme as a gem)
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
title_font: "Inter, system-ui, -apple-system, Segoe UI, Roboto"
