title: IRRI Bioinformatics Portal
description: One stop shop for IRRI bioinformatics

remote_theme: just-the-docs/just-the-docs

url: "https://nixborj.github.io"
baseurl: "/bioinfo"

search_enabled: true
heading_anchors: true
nav_sort: case_insensitive

plugins:
  - jekyll-remote-theme

aux_links:
  "IRRI Main Site":
    - "https://www.irri.org/"

nav_external_links:
  - title: Consultation
    url: https://www.google.com/
    opens_in_new_tab: true
